/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBox: typeof import('./components/base-box/index.vue')['default']
    BaseButton: typeof import('./components/base-button/index.vue')['default']
    BaseCharts: typeof import('./components/base-charts/src/base-charts.vue')['default']
    BaseCountTo: typeof import('./components/base-count-to/index.vue')['default']
    BaseDialog: typeof import('./components/base-dialog/src/base-dialog.vue')['default']
    BaseIcon: typeof import('./components/base-icon/base-icon.vue')['default']
    BaseIconPicker: typeof import('./components/base-icon/base-icon-picker.vue')['default']
    BaseLoading: typeof import('./components/base-loading/base-loading.vue')['default']
    BaseResult: typeof import('./components/base-result/base-result.vue')['default']
    BaseSeamScroll: typeof import('./components/base-seamscroll/src/base-seam-scroll.vue')['default']
    BaseSkeleton: typeof import('./components/base-skeleton/base-skeleton.vue')['default']
    ChaseSpin: typeof import('./components/base-loading/spin/chaseSpin.vue')['default']
    CubeSpin: typeof import('./components/base-loading/spin/cubeSpin.vue')['default']
    DotSpin: typeof import('./components/base-loading/spin/dotSpin.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PlaneSpin: typeof import('./components/base-loading/spin/planeSpin.vue')['default']
    PreloaderSpin: typeof import('./components/base-loading/spin/preloaderSpin.vue')['default']
    PulseSpin: typeof import('./components/base-loading/spin/pulseSpin.vue')['default']
    RectSpin: typeof import('./components/base-loading/spin/rectSpin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
